# Generated by Django 4.1.2 on 2022-10-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrest_key', models.PositiveBigIntegerField()),
                ('arrest_date', models.DateField()),
                ('pd_cd', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pd_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('ky_cd', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ofns_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('law_code', models.CharField(max_length=20)),
                ('law_cat_cd', models.CharField(choices=[('M', 'Misdemeanor'), ('F', 'Felony'), ('V', 'Violation'), (None, 'N/A')], default=None, max_length=1)),
                ('arrest_boro', models.CharField(choices=[('M', 'Manhattan'), ('K', 'Kings'), ('Q', 'Queens'), ('B', 'Bronx'), ('S', 'Staten Island'), (None, 'N/A')], default=None, max_length=1)),
                ('arrest_precint', models.PositiveSmallIntegerField()),
                ('jurisdiction_code', models.PositiveSmallIntegerField()),
                ('age_group', models.CharField(max_length=10)),
                ('perp_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), (None, 'None')], default=None, max_length=1)),
                ('perp_race', models.CharField(max_length=100)),
                ('x_coord_cd', models.IntegerField()),
                ('y_coord_cd', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=15)),
                ('long_lat', models.CharField(max_length=150)),
            ],
        ),
    ]
