# Generated by Django 4.1.2 on 2022-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nypd_arrests_api', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrests',
            name='arrest_date',
            field=models.CharField(max_length=10),
        ),
    ]
