# Generated by Django 4.1.2 on 2022-10-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nypd_arrests_api', '0003_alter_arrests_arrest_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrests',
            old_name='arrest_precint',
            new_name='arrest_precinct',
        ),
    ]
