# Generated by Django 4.1.2 on 2022-10-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nypd_arrests_api', '0005_boroughheatmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='boroughheatmap',
            name='arrest_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boroughheatmap',
            name='bronx_arrests',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boroughheatmap',
            name='kings_arrests',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boroughheatmap',
            name='manhattan_arrests',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boroughheatmap',
            name='queens_arrests',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boroughheatmap',
            name='staten_island_arrests',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
