# Generated by Django 4.1.2 on 2022-10-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nypd_arrests_api', '0007_alter_arrests_arrest_precinct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrests',
            name='ky_cd',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='arrests',
            name='ofns_desc',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='arrests',
            name='pd_cd',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='arrests',
            name='pd_desc',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
